### ISSUE TITLE
Follow up on initial puppet work

### ISSUE THREAD

**Issue by bertpareyn** [CUL-DigitalServices/grasshopper-puppet#4]
Follow up on the comments per review on https://github.com/CUL-DigitalServices/grasshopper-puppet/pull/3

**Comment by Coenego** [comment]
Is this something that still needs to happen @ucamrc ?

**Comment by ucamrc** [comment]
I don't think so, unless you want to go through the comments on #3 line by line to check if I've missed anything out!
